language: node_js
node_js:
- '0.10'
script: npm run-script deploy
env:
  global:
  - GH_REF: github.com/mozillafordevelopment/mobile-appmaker
  - secure: j6YlqyWYlxXnwgBroP9l/0grZ1PGv7hDYJWGDLuFScZUHRVv2TgzysGPxzxlee3uq3LYWjGOER8NtWuiOE8tyelbYYlUXzh/erTnBFzf2UzWo378u3TKqmkV7gtqp3ak/IdYCGBcSnbhDFMOIlKXMybb/eVMuomk/33IUqHd6EQ=
